[package]
name = "moc"
version = "0.8.4"
authors = ["Matthieu Baumann <matthieu.baumann@astro.unistra.fr>"]
edition = "2018"

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]

[lib]
name = "moc"
path = "src/lib.rs"
test = true
doctest = true
bench = true
crate-type = ["cdylib"]

[dependencies]
rand = "0.7.3"
intervals = { path = "./src/intervals" }
healpix = { package = "cdshealpix", git = 'https://github.com/cds-astro/cds-healpix-rust', branch = 'master' }
numpy = "0.9.0"
num = "0.2"
time = "*"
rayon = "1.3.0"
lazy_static = "1.4.0"

[dependencies.ndarray]
version = "0.13.1"
default-features = false # do not include the default features, and optionally
                         # cherry-pick individual features
features = ["rayon"]

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 0
