channels:
- defaults
- conda-forge

dependencies:
- astropy
- matplotlib
- pytest
- pytest-cov
- sphinx
- pip:
  - numpydoc
  - astropy-sphinx-theme
  - networkx
  - lark-parser
  - cdshealpix
  - astropy_healpix
